#!/usr/bin/env ruby

# Copyright 2016--2018, Raphael Reitzig
#
# canonimgnames is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# canonimgnames is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with canonimgnames. If not, see <http://www.gnu.org/licenses/>.

require 'fileutils'

DEBUG = false

def lineToDatetime(line)
  puts line if DEBUG
  parts = line.split(/\s+:\s+/)
  puts parts.to_s if DEBUG
  
  if parts.size >= 2
    if parts[0] == "Error"
      "Error"
    else
      datetime = parts[1].split(/\s+/)
      puts datetime.to_s if DEBUG
      date = datetime[0].strip.gsub(":", "-")
      time = datetime[1].split(/[\D]/)[0..2].join(".")
      "#{date} #{time}"
    end
  else
    "Error"
  end
end

renamed = 0
ARGV.each { |file|
  if File.exist?(file) && !File.directory?(file)
    puts file if DEBUG
    exif = `exiftool '#{file}' | grep -E "(Error|Create Date|Date/Time Original)"`
    if exif.strip.size > 0
      exif = exif.split("\n").map {|line| lineToDatetime(line) }
      if exif.include?("Error")
        next
      else  
        filename = "#{exif.max}.#{file.split(".").last}" # is that always the right thing to do?
        if filename != file && !File.exist?(filename)
          puts filename if DEBUG
          FileUtils::mv(file, File.dirname(file) + "/" + filename) unless DEBUG
          renamed += 1
        end
      end
    end
  end
  puts "" if DEBUG
}
puts "Renamed #{renamed}, skipped #{ARGV.size - renamed}"
