#!/usr/bin/ruby

require 'fileutils'

DEBUG = false

def lineToDatetime(line)
  puts line if DEBUG
  parts = line.split(/\s+:\s+/)
  puts parts.to_s if DEBUG
  
  if parts.size >= 2
    if parts[0] == "Error"
      "Error"
    else
      datetime = parts[1].split(/\s+/)
      puts datetime.to_s if DEBUG
      date = datetime[0].strip.gsub(":", "-")
      time = datetime[1].strip.gsub(":", ".")
      "#{date} #{time}"
    end
  else
    "Error"
  end
end

renamed = 0
ARGV.each { |file|
  if File.exist?(file) && !File.directory?(file)
    exif = `exiftool '#{file}' | grep -E "(Error|Create Date|Date/Time Original)"`
    if exif.strip.size > 0
      exif = exif.split("\n").map {|line| lineToDatetime(line) }
      if exif.include?("Error")
        next
      else  
        filename = exif.max # is that always the right thing to do?
        if filename != file && !File.exist?(filename)
          puts filename if DEBUG
          FileUtils::mv(file, File.dirname(file) + "/" + filename) unless DEBUG
          renamed += 1
        end
      end
    end
  end
  puts "" if DEBUG
}
puts "Renamed #{renamed}, skipped #{ARGV.size - renamed}"
