#!/bin/bash

# Copyright 2016--2018, Raphael Reitzig
#
# rmd2html is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# rmd2html is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with rmd2html. If not, see <http://www.gnu.org/licenses/>.

# A simple wrapper script that delegates to RMarkdown.

Rscript -e "rmarkdown::render('${1}')"

