#!/bin/bash

# Copyright 2015--2018 Raphael Reitzig
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>

# Requires: qrencode, display
#           For tiling workaround under i3, also: wmctrl, awk

# Shows text found as CLI parameters as a QR-code.
# If no parameters are given, reads from STDIN.

set -o pipefail

f=`mktemp --suff=.png`;

# Convert STDIN resp. first parameter 
if [ $# -eq 0 ]; then
  qrencode -o ${f} < /dev/stdin
else
  qrencode -o ${f} "$*";
fi

# Open the QR code for viewing
display ${f} & 
pid="$!"

# If i3 is active, trickery to get a floating viewer 
# instead of madness (cf. https://github.com/ImageMagick/ImageMagick/issues/1213).
if wmctrl -m | grep "Name: i3" > /dev/null; then
  # cf. https://unix.stackexchange.com/a/474300/17409 

  # Can't search for the PID (display doesn't tell it to wmctrl).
  # Turns out the window name is
  #
  #     ImageMagick: tmp.tmp.XXXX.png
  #
  # so we can use that to search for the window ID.
  # We use only the filename which ends up in its own column in awk.
  winname="`basename "${f}" | sed -e 's/\\//./'`"
  
  # Wait for the window to open
  winid=''
  while : ; do
    winid="`wmctrl -l | awk -vwinname="${winname}" '$5==winname  {print $1; exit}'`"
    [[ -z "${winid}" ]] || break
  done

  # Focus the window
  wmctrl -ia "${winid}"
  
  # Make it float
  i3-msg floating enable > /dev/null;
fi

# Wait for the user to close display and clean up
wait "${pid}";
rm ${f};

